export const tooltips: Record<string, string> = {
  cpu_gauge: 'Total CPU utilization across all cores -- 100% means all cores are fully busy',
  memory_gauge: 'Physical RAM usage -- how much of your installed memory is actively in use',
  swap: 'Swap space -- disk area used as overflow when RAM is full (high swap = memory pressure)',
  load_average: 'Average number of processes waiting to run -- compare to your core count to gauge system load',
  load_1m: '1-minute load average -- most recent snapshot of system demand',
  load_5m: '5-minute load average -- short-term trend of system demand',
  load_15m: '15-minute load average -- longer-term baseline of system demand',
  pid: 'Process ID -- unique number assigned by the OS to identify this process',
  ppid: 'Parent Process ID -- the process that created this one',
  cpu_percent: 'Percentage of CPU time this process used in the last sampling interval',
  memory_rss_bytes: 'Resident Set Size -- physical RAM actually being used right now',
  memory_vms_bytes: 'Virtual Memory Size -- total virtual memory mapped (much larger than RSS)',
  num_threads: 'Number of threads running inside this process',
  nice: 'Nice value (-20 to 19) -- lower means higher priority',
  ctx_switches_voluntary: 'Times this process gave up the CPU voluntarily (e.g., waiting for I/O)',
  ctx_switches_involuntary: 'Times the scheduler preempted this process (time slice expired)',
  status: 'Current state -- running, sleeping, zombie, stopped, etc.',
  tid: 'Thread ID -- unique number for this thread within the OS',
  core_id: 'Which CPU core this thread is currently running on',
  entity_type: 'Whether this entry represents a process or a thread',
  memory_shared_bytes: 'Shared memory -- memory that can be accessed by multiple processes',
  memory_text_bytes: 'Text segment -- memory used for the executable code of the process',
  memory_data_bytes: 'Data segment -- memory used for initialized and uninitialized data (heap + globals)',
  io_read_bytes: 'Total bytes read from disk by this process since it started',
  io_write_bytes: 'Total bytes written to disk by this process since it started',
  num_fds: 'Number of file descriptors currently open (files, sockets, pipes)',
  num_connections: 'Number of active network connections (TCP/UDP sockets)',
  num_open_files: 'Number of files currently open by this process',
  cpu_time_user: 'Total CPU time spent executing user-space code (not kernel code)',
  cpu_time_system: 'Total CPU time spent executing kernel-space code on behalf of this process',
  stack_size_bytes: 'Size of the thread stack in bytes -- memory reserved for function calls and local variables',
  memory_uss_bytes: 'Unique Set Size -- memory that is unique to this process and not shared',
  memory_pss_bytes: 'Proportional Set Size -- shared memory divided proportionally among all sharing processes',
  memory_percent: 'Percentage of total system RAM used by this process',
  memory_lib_bytes: 'Memory used by shared libraries loaded by this process',
  memory_dirty_bytes: 'Memory pages that have been modified but not yet written back to disk',
  io_read_count: 'Total number of read I/O operations performed by this process',
  io_write_count: 'Total number of write I/O operations performed by this process',
  cpu_time_children_user: 'CPU time in user mode consumed by waited-for children of this process',
  cpu_time_children_system: 'CPU time in kernel mode consumed by waited-for children of this process',
  cpu_time_iowait: 'Time the CPU spent waiting for I/O operations requested by this process',
  create_time: 'Unix timestamp of when this process was created',
  exe: 'Full path to the executable file that started this process',
  cmdline: 'Full command line used to launch this process, including arguments',
  username: 'The user account under which this process is running',
  priority: 'Scheduling priority of this thread as seen by the OS',
  voluntary_ctx_switches: 'Times this thread voluntarily yielded the CPU',
  involuntary_ctx_switches: 'Times this thread was forcibly preempted by the scheduler',
};
