export const tooltips: Record<string, string> = {
  cpu_gauge: 'Total CPU usage across all cores. 100% = every core fully busy.',
  memory_gauge: 'Physical RAM usage. Shows how much of your installed memory is in use.',
  swap: 'Disk overflow when RAM is full. High swap = memory pressure and slowdowns.',
  load_average: 'Average processes wanting to run. Compare to core count: load > cores = queuing.',
  load_1m: '1-min load average: most recent snapshot of system demand.',
  load_5m: '5-min load average: short-term demand trend.',
  load_15m: '15-min load average: longer-term baseline.',
  pid: 'Process ID -- unique number assigned by the OS to identify this process',
  ppid: 'Parent Process ID -- the process that created this one',
  cpu_percent: 'Percentage of CPU time this process used in the last sampling interval',
  memory_rss_bytes: 'Resident Set Size -- physical RAM actually being used right now',
  memory_vms_bytes: 'Virtual Memory Size -- total virtual memory mapped (much larger than RSS)',
  num_threads: 'Number of threads running inside this process',
  nice: 'Nice value (-20 to 19) -- lower means higher priority',
  ctx_switches_voluntary: 'Times this process gave up the CPU voluntarily (e.g., waiting for I/O)',
  ctx_switches_involuntary: 'Times the scheduler preempted this process (time slice expired)',
  status: 'Current state -- running, sleeping, zombie, stopped, etc.',
  tid: 'Thread ID -- unique number for this thread within the OS',
  core_id: 'Which CPU core this thread is currently running on',
  entity_type: 'Whether this entry represents a process or a thread',
  memory_shared_bytes: 'Shared memory -- memory that can be accessed by multiple processes',
  memory_text_bytes: 'Text segment -- memory used for the executable code of the process',
  memory_data_bytes: 'Data segment -- memory used for initialized and uninitialized data (heap + globals)',
  io_read_bytes: 'Total bytes read from disk by this process since it started',
  io_write_bytes: 'Total bytes written to disk by this process since it started',
  num_fds: 'Number of file descriptors currently open (files, sockets, pipes)',
  num_connections: 'Number of active network connections (TCP/UDP sockets)',
  num_open_files: 'Number of files currently open by this process',
  cpu_time_user: 'Total CPU time spent executing user-space code (not kernel code)',
  cpu_time_system: 'Total CPU time spent executing kernel-space code on behalf of this process',
  stack_size_bytes: 'Size of the thread stack in bytes -- memory reserved for function calls and local variables',
  memory_uss_bytes: 'Unique Set Size -- memory that is unique to this process and not shared',
  memory_pss_bytes: 'Proportional Set Size -- shared memory divided proportionally among all sharing processes',
  memory_percent: 'Percentage of total system RAM used by this process',
  memory_lib_bytes: 'Memory used by shared libraries loaded by this process',
  memory_dirty_bytes: 'Memory pages that have been modified but not yet written back to disk',
  io_read_count: 'Total number of read I/O operations performed by this process',
  io_write_count: 'Total number of write I/O operations performed by this process',
  io_read_rate: 'Current disk read throughput in bytes per second (calculated between ticks)',
  io_write_rate: 'Current disk write throughput in bytes per second (calculated between ticks)',
  io_read_ops_rate: 'Current read operations per second (calculated between ticks)',
  io_write_ops_rate: 'Current write operations per second (calculated between ticks)',
  cpu_time_children_user: 'CPU time in user mode consumed by waited-for children of this process',
  cpu_time_children_system: 'CPU time in kernel mode consumed by waited-for children of this process',
  cpu_time_iowait: 'Time the CPU spent waiting for I/O operations requested by this process',
  create_time: 'Unix timestamp of when this process was created',
  exe: 'Full path to the executable file that started this process',
  cmdline: 'Full command line used to launch this process, including arguments',
  username: 'The user account under which this process is running',
  priority: 'Scheduling priority of this thread as seen by the OS',
  voluntary_ctx_switches: 'Times this thread voluntarily yielded the CPU',
  involuntary_ctx_switches: 'Times this thread was forcibly preempted by the scheduler',

  /* ── CPU Cores page ─────────────────────────────────────────────── */
  cpu_page_title: 'Deep dive into how your processor handles work across all cores.',
  cpu_processor: 'Physical (P) vs Logical (L) cores. Logical includes hyper-threaded virtual cores. More cores = more parallel tasks.',
  cpu_frequency: 'Current clock speed in MHz. The range shows min/max the CPU can reach. Higher = faster single-threaded work.',
  cpu_per_core_usage: 'How busy each individual core is right now. Uneven bars = workload isn\'t well-parallelized.',
  cpu_usage_over_time: 'Rolling history of total CPU usage. Spot trends, spikes, and sustained high-load periods.',
  cpu_heatmap: 'Color grid: each cell = one core at one point in time. Warmer = higher usage. Spot which cores are being hammered.',
  cpu_top_consumers: 'Top 10 processes by CPU usage. Click a row to see details.',
  cpu_top_name: 'The executable name of this process.',
  cpu_top_memory: 'RSS: physical RAM this process is using right now.',
  cpu_top_threads: 'Thread count. More threads = more parallel work.',
  cpu_top_user: 'The OS user account running this process.',

  /* ── Memory View page ───────────────────────────────────────────── */
  mem_page_title: 'Detailed view of how your system\'s RAM and swap are being used.',
  mem_used: 'Physical RAM actively in use by apps and OS. High usage is normal — the OS uses RAM efficiently.',
  mem_available: 'RAM that can be given to apps immediately (free + reclaimable cache). Better indicator than "free" for headroom.',
  mem_swap_card: 'When RAM fills up, the OS moves pages to disk (swap). High swap = slowdowns since disk is much slower than RAM.',
  mem_breakdown: 'Stacked bar showing how RAM is divided. Hover each segment to see its size.',
  mem_wired: 'Wired (macOS): memory locked in RAM, cannot be swapped. Used by kernel and critical structures.',
  mem_compressed: 'Compressed (macOS): pages compressed in RAM to save space without swapping to disk.',
  mem_app_memory: 'App Memory (macOS): RAM actively used by your applications.',
  mem_cached: 'Cached: disk data kept in RAM for speed. Reclaimable if apps need it — high cache is fine.',
  mem_buffers: 'Buffers: temporary storage for raw disk I/O. Usually small.',
  mem_shared: 'Shared: RAM accessible by multiple processes (shared libs, IPC regions).',
  mem_free: 'Truly unused RAM. Often low on healthy systems because the OS caches aggressively. Check "Available" instead.',
  mem_usage_over_time: 'Rolling history of RAM %. Spot memory leaks (steady climb) or sudden spikes.',
  mem_swap_over_time: 'Rolling history of swap %. Rising swap = system running out of physical RAM.',
  mem_detailed_stats: 'Every memory metric reported by your OS in one grid.',
  mem_physical: 'Total physical RAM installed in your system.',
  mem_usage_percent: 'How much of total RAM is in use, as a percentage.',
  mem_swap_total: 'Total swap space configured (swap partition or file).',
  mem_swap_used: 'Swap space currently occupied by pages moved out of RAM.',
  mem_swap_free: 'Remaining swap space. If this hits zero and RAM is full, allocations may fail.',
  mem_swap_usage: 'Proportion of total swap currently in use.',
  mem_top_consumers: 'Top 10 processes by RAM usage. Click a row to see details.',
  mem_top_name: 'The executable name of this process.',
  mem_top_rss: 'RSS: physical RAM pages held by this process.',
  mem_top_virtual: 'VMS: total virtual address space. Much larger than RSS (includes mapped files, reserved regions).',
  mem_top_mem_pct: 'Fraction of total system RAM used by this process.',
  mem_top_cpu_pct: 'CPU time used by this process in the last sampling interval.',
  mem_top_user: 'The OS user account running this process.',
};
